on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    name: Test the speccy lint
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test against pet store (should fail)
        continue-on-error: true
        uses: ./ # Uses an action in the root directory
        with:
          path: '.github/petstore.yaml'